name: Experienced
main: cc.isotopestudio.Experienced.Experienced

author: Mars
description: Experienced
website: http://isotopestudio.cc
version: 1.0.2
commands:
  expstore:
    description: Experienced command
    usage: /<command> - Get Information
    aliases: expchucun
  expget:
    description: Experienced command
    usage: /<command> - Get Information
    aliases: expshiyong